language: python
# PIP is a package manager for Python packages and/or modules.
cache: pip

python:
  - 3.7.1
  
env:
  - DJANGO_VERSION==2.1.3

dist:
  - xenial
  
services:
  - db.sqlite3

before_script:
  - touch travis_ci_db # creates a flat file you can use for your SQLite DB
  - python manage.py migrate

# command to run tests
script:
  - python manage.py test
