language: python
# PIP is a package manager for Python packages and/or modules.
cache: pip

python:
  - 3.7.1
  
env:
  - DJANGO_VERSION==2.1.3

#- pip install -r ...  
install:
 - pip install -r requirements.txt
 
notifications:
    on_success: always
    on_failure: always

services:
  - sqlite3
 
# use manage.py to start a local server
before_script:
  - sqlite3 -e -u root

# command to run tests
script:
  - python manage.py test travis
 
after_script:
 - coveralls
