language: python
# PIP is a package manager for Python packages and/or modules.
cache: pip

python:
  - 3.7.1
  
#- pip install -r ...  
install:
 - pip install -r requirements.txt
 
notifications:
    on_success: always
    on_failure: always
 
# use manage.py to start a local server
# before_script:

# command to run tests
script:
  - coverage run manage.py test
   - coverage run functional_tests.py
  #- "./functional_tests.py"
 
after_script:
 - coveralls
