language: python
# PIP is a package manager for Python packages and/or modules.
cache: pip

python:
  - 3.7.1
  
env:
  - DJANGO_VERSION==2.1.3

#- pip install -r ...  
install:
 - pip install -q Django==$DJANGO
 - pip install -r requirements.txt
 
services:
  - db.sqlite3

before_script:
  - sqlite3 -e 'create database travis_ci_db;'
  - python manage.py syncdb --noinput

# command to run tests
script:
  - python manage.py test travis
