language: python
# PIP is a package manager for Python packages and/or modules.
cache: pip

python:
  - 3.7.1
  
env:
  - DJANGO_VERSION==2.1.3

#- pip install -r ...  
install:
 - pip install -r requirements.txt
 
services:
  - sqlite3

# command to run tests
script:
  - python manage.py test travis