language: python
# PIP is a package manager for Python packages and/or modules.
cache: pip

python:
  - 3.7.1
  
env:
  - DJANGO_VERSION==2.1.3

dist:
  - xenial
  
services:
  - db.sqlite3

before_script:
  - sqlite3 travis_ci_db # creates a new database called `travis_ci_db`
  - python manage.py syncdb

# command to run tests
script:
  - python manage.py travis
